In [1]:
import torch
import numpy as np

# 텐서 초기화

In [4]:
# 데이터로부터 직접 생성하기 (directly)
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
# numpy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [16]:
# 다른 텐서로부터 생성하기 => 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지
x_ones = torch.ones_like(x_data) # x_data의 속성 유지 (모양, 자료형 그대로 원소 1)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 dtype 변경
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8800, 0.3651],
        [0.5817, 0.8308]]) 



In [17]:
# 무작위(random) 또는 상수(constant)값을 이용한 생성

shape = (2,3,) # 텐서의 차원을 나타내는 tuple
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2970, 0.5369, 0.1436],
        [0.8700, 0.4064, 0.8677]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 텐서의 속성 (Attribute)


In [20]:
# 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타낸다.
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}") # shape(모양) 확인
print(f"Datatype of tensor: {tensor.dtype}") # 자료형 확인
print(f"Device tensor is stored on: {tensor.device}") # 어느 장치에 저장되는지 ex) gpu, cpu

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# 텐서 연산(Operation)

[토치 관련 연산 확인]

https://pytorch.org/docs/stable/torch.html 

In [22]:
# GPU가 존재하면 텐서를 이동  , 기본적으로 텐서는 cpu에 생성
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [24]:
# numpy 식의 표준 인덱싱 및 슬라이싱

tensor = torch.ones(4, 4) # 4*4 Shape의 모든 원소가 1 인 torch 생성
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0 # Second Column 의 원소들을 0으로 
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


[torch.stack]

https://pytorch.org/docs/stable/generated/torch.stack.html

In [35]:
# 텐서 합치기 torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결 
# torch.stack 과는 다름
print("Using cat method")
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)
print(t1)

t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2.shape)
print(t2)

# torch.stack
print("\nUsing stack method") # 3차원의 tensor가 만들어진 것을 확인
t3 = torch.stack([tensor, tensor, tensor], dim=1)
print(t3.shape)
print(t3)

t4 = torch.stack([tensor, tensor, tensor], dim=0)
print(t4.shape)
print(t4)

Using cat method
torch.Size([4, 12])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([12, 4])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Using stack method
torch.Size([4, 3, 4])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([3, 4, 4])
t

In [51]:
# 산술 연산(Arithmetic operations)

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산 
print("[ matrix multiplication ]")
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3) # out = y3을 통해 y3에 결과 저장
print(y3)


# 요소별 곱(element-wise product)을 계산
print("\n[ element-wise product ]")
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3) # out = z3을 통해 z3에 결과 저장
print(z3)

[ matrix multiplication ]
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.8777, 0.1843, 0.0943, 0.5050],
        [0.7959, 0.4853, 0.7392, 0.7659],
        [0.1348, 0.1375, 0.2602, 0.1981],
        [0.5177, 0.3875, 0.0459, 0.6317]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

[ element-wise product ]
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.9889, 0.6315, 0.3156, 0.2516],
        [0.4048, 0.9346, 0.9668, 0.7287],
        [0.2098, 0.0652, 0.2703, 0.0692],
        [0.7696, 0.5693, 0.0512, 0.7784]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
       

단일-요소(single-element) 텐서

- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환

In [58]:
# 단일 요소 텐서
agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

# tensor_item = tensor.item() => element가 하나가 아니기 때문에 에러
# only one element tensors can be converted to Python scalars

tensor(12.)
12.0 <class 'float'>


바꿔치기(in-place) 연산 
- 연산 결과를 피연산자(operand)에 저장하는 연산
- _ 접미사를 갖는다. 
- ex : x.copy_(y) 나 x.t_() 는 x 를 변경

바꿔치기 연산은 메모리를 일부 절약 But 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있다. 따라서, 사용 굳이 XXX

In [64]:
print(tensor, "\n") # 피연산자 tensor
tensor.add_(5) # add_ => _ 접미사
print(tensor)

tensor.copy_(z3)
print()
print(tensor)

tensor.t_() # transpose
print()
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# Numpy 변환(Bridge)

주의 !!!!! 

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경

In [73]:
# 텐서를 Numpy 배열로
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [74]:
t.add_(1)  # 텐서의 각 원소에 1을 더함
print(f"t: {t}")
print(f"n: {n}")  # numpy 배열또한 변경

n[0] += 1 # numpy 배열의 첫번째 원소에 1을 더함
print(t) # tensor 또한 변경
print(n)

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
tensor([3., 2., 2., 2., 2.])
[3. 2. 2. 2. 2.]


In [79]:
# Numpy 배열을 텐서로
n = np.ones(5)
t = torch.from_numpy(n)

print(f"t: {t}")
print(f"n: {n}") 

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [80]:
# 마찬가지로 numpy 배열 변경해보기
np.add(n, 1, out=n)
print(f"t: {t}") # tensor 변경사항 확인
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
